# Generated by Django 4.1.4 on 2023-02-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
