# Generated by Django 4.1.4 on 2023-02-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stph', '0002_alter_contact_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
